### PR TITLE
change script path from /var/log to /var/tmp

### PR DESCRIPTION
**Pull request by oneilcin**
We ran into permission problems in aws.  With /var/tmp the scripts will copy

### CODE REVIEW

**Comment by davidewatson** [comment]
Is this secure though? Have we tried changing SSHConfig user from `ubuntu` to `root`?

**Comment by notjames** [comment]
@davidewatson is security something we need to worry about for these scripts? If so, we could copy them over, run them, on successful run, shred them.
Is far better to put the scripts in /var/tmp than /var/log IMHO.

**Comment by philoserf** [comment]
I only see a change in directory here. Any user change is external to this code. Unless I missed a user reference.

**Comment by oneilcin** [comment]
I only changed the directory where the script will be copied to the remote node.

**Comment by davidewatson** [comment]
This PR does more than just change the directory. It changes the permissions which govern access to the file.

To determine the right location for these scripts we should follow the [Filesystem Hierarchy Standard](http://www.pathname.com/fhs/pub/fhs-2.3.html#THEVARHIERARCHY).

**Comment by davidewatson** [comment]
`/var/run` is probably proper.

**Comment by notjames** [comment]
> `/var/run` is probably proper.

You will still have to run as root to store the file in `/var/run`, which on the AWS instances will require `sudo` and then you'll need to change permissions of the file in order to run it as a normal user as `/var/run` has the same permissions as `/var/log` it seems.

**Pull request merged**
